### ISSUE TITLE
There are new translations at Quran.com

### ISSUE THREAD

**Issue by TarikHaci** [galacticwarrior9/IslamBot#10]
Esselamu aleykum we rahmetullahi we berekatuh brothers!
Today I have notices that Dutch -> M. F. Abdul Islam is added, could you add that also here?
Thank you in advance.
We aleykum esselam we rahmetullahi we berekatuh

**Comment by galacticwarrior9** [comment]
Walaikum assalam wa rahmatullahi wa barakatuh. 

Thank you for letting me know. It appears quran.com has, in fact, overhauled their entire API, so I will work on implementing its new features (including the translation you mentioned) next week.
