### ISSUE TITLE
Notice on the CMD problem. 

### ISSUE THREAD

**Issue by DeeZyL** [galacticwarrior9/IslamBot#22]
![Screenshot_20210805_053527](https://user-images.githubusercontent.com/82864812/128258179-e4578e8d-a735-4425-b247-fc71e21bd3f8.jpg)

**Comment by galacticwarrior9** [comment]
Salaam, you're using the commands incorrectly. 

The format is as follows:
```python
-tafsir <surah number>:<ayah number> <tafsir name>
```

`<tafsir name>` is optional. Leave it blank if you want to use the default tafsir (Ma'ariful Qur'an). 

See the [wiki page](https://github.com/galacticwarrior9/IslamBot/wiki/Tafsir) for more information. 

Examples:

`-tafsir 1:1 ibnkathir` for Ibn Kathir's tafsir on first verse of *Surah al-Fatiha*.

`-tafsir 2:255` for the tafsir of *Ayat al-Kursi*.
