### ISSUE TITLE
Error getting hadith from Forty Hadith of an-Nawawi

### ISSUE THREAD

**Issue by msabur** [galacticwarrior9/islambot#27]
When I use the command `-hadith nawawi 1`, the bot says that the hadith can't be found. I looked into it a bit, and it seems that the API was giving a 404 response. A possible solution is using "forty" instead of "nawawi40" as the collection name when making the request. That solved the error for me.
`https://api.sunnah.com/v1/collections/nawawi40/hadiths/1` returned 404
`https://api.sunnah.com/v1/collections/forty/hadiths/1` gave the hadith

May Allah reward you for your amazing work

**Comment by galacticwarrior9** [comment]
This is strange as `nawawi40` is still returned as a valid collection from the [collections list endpoint](https://sunnah.api-docs.io/1.0/collections/get-the-list-of-collections). I'll give this a few days and implement the workaround you proposed if the problem has still not been rectified on the API side by then.

**Comment by galacticwarrior9** [comment]
Fixed by https://github.com/galacticwarrior9/IslamBot/commit/af8283f6425b45fe53315d1dabf440a79c8a1b14
