### ISSUE TITLE
Option to specify the quranic sura numbers according to the chronological order or by name

### ISSUE THREAD

**Issue by erkinalp** [galacticwarrior9/IslamBot#5]

**Comment by Khalifa1997** [comment]
Can you elaborate?

**Comment by erkinalp** [comment]
Each surah in Quran has a traditional name. And surahs appeared in a different order from the canonical order that appears in Quran.

**Comment by itzmk21** [comment]
So, when doing -quran 1:1, it shows Surah Iqra instead of Surah Fatihah, and users have the option of that in settings/config?

**Comment by erkinalp** [comment]
Yes the chronological ordering would work like that.

**Comment by itzmk21** [comment]
Will try to implement this with slash commands, since having another optional parameter is so much easier with them
(The by chronological number)

**Comment by itzmk21** [comment]
Name should be possible by making the parameter `surah` a string and, similar to how Iqra does it, try to convert to a number and if not then, use fuzzywuz to get the Surah name
