### ISSUE TITLE
Bot not notifying user when requested ayah number is too high

### ISSUE THREAD

**Issue by msabur** [galacticwarrior9/islambot#52]
The bot doesn't notify the user when the requested ayah number is more than the number of ayahs in the surah. 
An example is `-quran 12:400`. The surah has less than 400 ayahs.

**Comment by msabur** [comment]
There is an invalid ayah message in quran.py, but it doesn't seem to be sending. https://github.com/galacticwarrior9/IslamBot/blob/master/quran/quran.py#L25

**Comment by itzmk21** [comment]
I remember that working before. I think the whole reveal surah argument commit broke it.

**Comment by msabur** [comment]
It was fixed for me after removing the `InvalidAyah` class in [quran.py](https://github.com/galacticwarrior9/IslamBot/blob/master/quran/quran.py#L40). Apparently, that was shadowing the identically-named class in [quran_info.py](https://github.com/galacticwarrior9/IslamBot/blob/master/quran/quran_info.py#L483). As a result, when the InvalidAyah exception was [thrown](https://github.com/galacticwarrior9/IslamBot/blob/master/quran/quran_info.py#L544), the [isInstance call](https://github.com/galacticwarrior9/IslamBot/blob/master/quran/quran.py#L306) was comparing to the wrong class.
