### ISSUE TITLE
Muhammad Asad translation?

### ISSUE THREAD

**Issue by babloyi** [galacticwarrior9/islambot#74]
Can it be included in the list of English translations? I'm not sure how the translations are selected, and which ones are ok to include. If it is a matter of time and effort, I could perhaps help in some way?

**Comment by galacticwarrior9** [comment]
Hi,

IslamBot uses the quran.com API to retrieve translations. Muhammad Asad's translation is not provided through the API - nor, indeed, the website itself - so I am unable to add it to the bot in its present form. [You can request it to be added to quran.com through their feedback forum.](https://feedback.quran.com/translation-and-reciter-requests)
