### ISSUE TITLE
Prayer times error messages not being ephemeral

### ISSUE THREAD

**Issue by itzmk21** [galacticwarrior9/islambot#87]
I think the reason for prayertimes command being ephemeral was to hide users locations from others. However the error message for Location Not Found isn't ephemeral and therefore shows the location in the slash command.

**Comment by galacticwarrior9** [comment]
Fixed by https://github.com/galacticwarrior9/IslamBot/commit/84e3831fbcedea6c472a27d31bdd5b80ce094d54
