### ISSUE TITLE
Use application commands

### ISSUE THREAD

**Issue by erkinalp** [galacticwarrior9/IslamBot#9]
Using application commands will reduce total resource use by not scanning all the messages.

**Comment by galacticwarrior9** [comment]
Can you elaborate? Do you mean the `Bot.command()` decorator? If so, the bot already uses it to register commands

**Comment by erkinalp** [comment]
No, I mean this: https://github.com/discord/discord-api-docs/pull/2295/

**Comment by galacticwarrior9** [comment]
Closing for now since discord.py does not support slash commands. Their functionality also appears to be too limited for the bot at the moment. However, thanks for the suggestion. I will definitely review this again if they improve in the future.
